/* Juan Manuel Tomás - 232063 */
package sumas;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class FrameTablero extends javax.swing.JFrame implements Observer {

    private JButton[][] celdas;
    private Sistema sistema;
    private Partida partida;
    private Comando comando;

    public FrameTablero() {
        initComponents();
        this.setTitle("Frame Tablero");
        this.getContentPane().setBackground(new Color(0x222222));
    }

    public FrameTablero(Sistema sistema, Partida partida) {
        this();
        this.sistema = sistema;
        this.partida = partida;
        this.comando = new Comando();
        this.panelJuego.setLayout(new GridLayout(8, 9));
        this.celdas = new JButton[9][10];
        for (int i = 1; i <= 8; i++) {
            for (int j = 1; j <= 9; j++) {
                JButton jButton = new JButton();
                jButton.setMargin(new Insets(-5, -5, -5, -5));
                jButton.setForeground(Color.white);
                jButton.addActionListener(new ListenerCelda(i, j, this.partida, this.comando));
                this.panelJuego.add(jButton);
                this.celdas[i][j] = jButton;
            }
        }
        this.panelBotones.setLayout(new FlowLayout());
        if (!partida.isRepeticion()) {
            this.agregarBoton("Saltar turno", 0);
            this.agregarBoton("Terminar partida", 1);
        } else {
            this.agregarBoton("Replicar jugada", 2);
            this.agregarBoton("Nueva partida", 3);
        }
    }

    private void agregarBoton(String texto, int tipo) {
        JButton boton = new JButton();
        boton.addActionListener(new ListenerBoton(this.sistema, this.partida, tipo, this.comando));
        boton.setText(texto);
        boton.setForeground(Color.white);
        boton.setBackground(Color.gray);
        this.panelBotones.add(boton);
    }

    @Override
    public void update(Observable obs, Object obj) {
        this.partida = (Partida) obs;
        Tablero tablero = this.partida.getTablero();
        for (int i = 1; i <= 8; i++) {
            for (int j = 1; j <= 9; j++) {
                switch (tablero.piezaCoord(i, j).getColor()) {
                    case "rojo":
                        this.celdas[i][j].setBackground(new Color(0xAA5555));
                        break;
                    case "azul":
                        this.celdas[i][j].setBackground(new Color(0x5555AA));
                        break;
                    default:
                        this.celdas[i][j].setBackground(Color.lightGray);
                        break;
                }
                int valor = tablero.piezaCoord(i, j).getValor();
                if (valor != 0) {
                    this.celdas[i][j].setText(Integer.toString(valor));
                } else {
                    this.celdas[i][j].setText("");
                }
            }
        }
        if (!tablero.getPosibles().isEmpty()) {
            StringBuilder s = new StringBuilder();
            s.append("Piezas que se pueden mover:");
            tablero.getPosibles().stream().forEach((pieza) -> {
                s.append(" ").append(pieza.getValor());
            });
            this.statusBar.setText(s.toString());
        } else {
            this.statusBar.setText("");
        }
        this.labelJugadorActual.setText(partida.getActual());
        if (partida.isFinPartida()) {
            Sonido s = new Sonido("Tada");
            JOptionPane.showMessageDialog(this, partida.getActual() + " ganó.");
            partida.deleteObserver(this);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        statusBar = new javax.swing.JLabel();
        labelJugadorActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelBotones.setBackground(new java.awt.Color(34, 34, 34));
        panelBotones.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(panelBotones);
        panelBotones.setBounds(570, 40, 120, 380);

        panelJuego.setBackground(new java.awt.Color(34, 34, 34));
        panelJuego.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(panelJuego);
        panelJuego.setBounds(20, 40, 530, 380);

        statusBar.setBackground(new java.awt.Color(22, 22, 22));
        statusBar.setForeground(new java.awt.Color(255, 255, 255));
        statusBar.setText("statusBar");
        getContentPane().add(statusBar);
        statusBar.setBounds(40, 430, 630, 20);

        labelJugadorActual.setBackground(new java.awt.Color(22, 22, 22));
        labelJugadorActual.setForeground(new java.awt.Color(255, 255, 255));
        labelJugadorActual.setText("jugadorActual");
        getContentPane().add(labelJugadorActual);
        labelJugadorActual.setBounds(50, 10, 150, 20);

        setSize(new java.awt.Dimension(713, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameTablero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelJugadorActual;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables

    private static class ListenerCelda implements ActionListener {

        private final int fila;
        private final int columna;
        private final Partida partida;
        private final Comando cmd;

        public ListenerCelda(int i, int j, Partida p, Comando cmd) {
            this.fila = i;
            this.columna = j;
            this.partida = p;
            this.cmd = cmd;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Sonido s;
            if (!this.partida.isRepeticion()) {
                Tablero t = this.partida.getTablero();
                if (this.cmd.getTipo() == -1) {
                    Pieza pieza = t.piezaCoord(this.fila, this.columna);
                    this.cmd.setTarget(pieza);
                    if (pieza.getValor() != 0
                            && pieza.getColor().equals(this.partida.getActual())
                            && (t.getPosibles().isEmpty() || t.getPosibles().contains(pieza))) {
                        this.cmd.setFila(this.fila);
                        this.cmd.setColumna(this.columna);
                        this.cmd.setTipo(0);
                        s = new Sonido("Command");
                    } else {
                        this.cmd.setTipo(-1);
                        s = new Sonido("Balloon");
                    }
                } else {
                    this.cmd.changeFila(this.fila);
                    this.cmd.changeColumna(this.columna);
                    if (this.cmd.validarComando(this.partida) == 0) {
                        s = new Sonido("Command");
                        this.partida.ejecutarComando(this.cmd);
                    } else {
                        s = new Sonido("Balloon");
                    }
                    this.cmd.setTipo(-1);
                }
            }
        }
    }

    private static class ListenerBoton implements ActionListener {

        private final Sistema sistema;
        private final Partida partida;
        private final Comando cmd;
        private final int tipo;

        public ListenerBoton(Sistema sistema, Partida partida, int tipo, Comando cmd) {
            this.sistema = sistema;
            this.partida = partida;
            this.tipo = tipo;
            this.cmd = cmd;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Sonido s;
            switch (this.tipo) {
                case 0:
                    this.cmd.setTipo(2);
                    if (this.cmd.validarComando(this.partida) == 0) {
                        s = new Sonido("Command");
                        this.partida.ejecutarComando(this.cmd);
                    }
                    break;
                case 1:
                    this.cmd.setTipo(1);
                    this.partida.ejecutarComando(this.cmd);
                    break;
                case 2:
                    s = new Sonido("Command");
                    this.partida.ejecutarComando(this.partida.pop());
                    break;
                case 3:
                    FramePartida frame = new FramePartida(this.sistema, this.partida);
                    frame.setVisible(true);
            }
            this.cmd.setTipo(-1);
        }
    }

}
