/* Juan Manuel Tomás - 232063 */
package sumas;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Collections;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan
 */
public class FrameRanking extends javax.swing.JFrame implements Observer {

    private Sistema sistema;

    public FrameRanking() {
        initComponents();
        this.setTitle("Frame Ranking");
        this.getContentPane().setBackground(new Color(0x222222));
    }

    public FrameRanking(Sistema sistema) {
        this();
        this.sistema = sistema;
        this.generarTabla();
    }

    private void generarTabla() {
        Collections.sort(this.sistema.getJugadores());
        UneditableModel jugadores = new UneditableModel();
        jugadores.addColumn("Nombre");
        jugadores.addColumn("Alias");
        jugadores.addColumn("Edad");
        jugadores.addColumn("Puntaje");
        for (Jugador j : this.sistema.getJugadores()) {
            Object[] data = {j.getNombre(), j.getAlias(), j.getEdad(), j.getPuntaje()};
            jugadores.addRow(data);
        }
        this.tablaJugadores.setModel(jugadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        botonExportar = new javax.swing.JButton();
        paneJugadores = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        botonSalir.setBackground(java.awt.Color.gray);
        botonSalir.setForeground(java.awt.Color.white);
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(40, 260, 70, 25);

        botonExportar.setBackground(java.awt.Color.gray);
        botonExportar.setForeground(java.awt.Color.white);
        botonExportar.setText("Exportar");
        botonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExportarActionPerformed(evt);
            }
        });
        getContentPane().add(botonExportar);
        botonExportar.setBounds(270, 260, 94, 25);

        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaJugadores.setRowSelectionAllowed(false);
        paneJugadores.setViewportView(tablaJugadores);

        getContentPane().add(paneJugadores);
        paneJugadores.setBounds(20, 40, 360, 210);

        jLabel1.setBackground(null);
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Ranking");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 70, 15);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExportarActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            try {
                FileWriter fw;
                if (file.getName().contains(".json")) {
                    fw = new FileWriter(file);
                } else {
                    fw = new FileWriter(file.getAbsolutePath() + ".json");
                }
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(this.sistema.jugadoresJson());
                bw.flush();
            } catch (IOException ex) {
                Sonido.reproducir("Error");
                JOptionPane.showMessageDialog(this, "No se pudo exportar el archivo.");
            }
        }
    }//GEN-LAST:event_botonExportarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.sistema.deleteObserver(this);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameRanking().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExportar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane paneJugadores;
    private javax.swing.JTable tablaJugadores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.generarTabla();
    }
    
    private class UneditableModel extends DefaultTableModel {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
}
